### ISSUE TITLE
browser_start_url should be fallback page

### ISSUE THREAD

**Issue by StanBarrows** [StanBarrows/raspberry-adscreens#20]
- [x] browser_start_url should be fallback page

```
screenurls:
  base: https://promoscreens.codebar.ch
  identification: /api/identification
  browser_start_url: https://www.python.org/dev/peps/pep-0020/#id2
  fallback: offlinefallback/index.html #* To prevent filesystem problems with /home/pi/Offline/index.html we add the fallbackpage into the python package and call it by its relativ path
```
